name: fp
version: 0.1.1
author: Victor Savkin <vic.savkin@gmail.com>
homepage: https://github.com/vsavkin/fpdart
description: >
  A library enabling functional programming in Dart similar to Underscore.js.
dependencies:
  unittest: ">= 0.5.0"