name: fp
version: 0.4.1
author: Victor Savkin <vic.savkin@gmail.com>
homepage: https://github.com/vsavkin/fpdart
description: >
  Functional programming helpers for Dart.
dependencies:
  unittest: '>=0.10.1 <0.12.0'
environment:
  sdk: ">=1.4.0 <2.0.0"