name: fp
version: 0.2.0
author: Victor Savkin <vic.savkin@gmail.com>
homepage: https://github.com/vsavkin/fpdart
description: >
  A library enabling functional programming in Dart.
dependencies:
  unittest: ">= 0.5.0"
environment:
  sdk: ">=0.8.7 <2.0.0"